TEST: Bring back Python 3.8 testing to GHA workflows
Bring back Python 3.8 testing to GHA workflows.

Removed in commit cf4338d.

Raise the minimum required NumPy version for the Python 3.8
compatibility test to 1.23.0 from the previously required 1.22.0 version
in commit 318bfc6 so that tests can pass. Fixes:
```
ImportError: numpy.core.multiarray failed to import
```

raised for example in:
https://github.com/dipy/dipy/actions/runs/6620737573/job/17983666930#step:9:12437